table Plant
	lineageTag: 8321eff4-6628-4871-8b7f-78dd628de8a4

	column 'Plant ID'
		dataType: int64
		formatString: 0
		lineageTag: a67fdf18-a124-4174-96ea-9eee56070d47
		summarizeBy: none
		sourceColumn: Plant ID

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 2609b0bd-3b47-46ad-b3b4-48db3b69bafa
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 325a986f-b468-4bdb-ab6f-c7ef1e27f927
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	partition Plant = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("T:\Users\tnaughton\Downloads\Data File J35 v2-1.xlsx"), null, true),
				    Plant_Sheet = Source{[Item="Plant",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Plant_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Plant ID", Int64.Type}, {"City", type text}, {"State", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

