table TransactionTable
	lineageTag: 8bb34e77-0c42-4d03-9242-72c1a3a08da8

	column Segment
		dataType: string
		lineageTag: 9802cbca-9f0b-47fe-8e72-5eeeb4b4ce37
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: df87a0a1-66cf-4a27-85cc-a3fb78538ab0
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: a4ccc8f4-4ff3-4599-a6c1-6da9aa37dcff
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Discount Category'
		dataType: string
		lineageTag: e420328f-49cf-4cc8-b6db-affe407ad993
		summarizeBy: none
		sourceColumn: Discount Category

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: int64
		lineageTag: 9761d524-ef4a-436d-8109-2fce0f131001
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Manufacturing Price'
		dataType: int64
		formatString: #,0
		lineageTag: 9275ce22-23c9-46df-8005-b083da71c4f4
		summarizeBy: sum
		sourceColumn: Manufacturing Price

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column 'Sale Price'
		dataType: int64
		formatString: 0
		lineageTag: 05a44c53-4ae1-4f79-a4b6-55ec1ab6ea45
		summarizeBy: sum
		sourceColumn: Sale Price

		annotation SummarizationSetBy = Automatic

	column 'Gross Sales'
		dataType: double
		lineageTag: 3f3a8084-ee1c-41fb-af5e-6c0d33c40204
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discounts
		dataType: double
		lineageTag: 6e1c7db7-d183-42b3-a7a1-b33d5bb76065
		summarizeBy: sum
		sourceColumn: Discounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ' Sales'
		dataType: double
		lineageTag: a03a9903-2b57-4136-9057-7ad1a029ed89
		summarizeBy: sum
		sourceColumn: " Sales"

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COGS
		dataType: double
		lineageTag: dd5aeb62-066c-41db-80e5-619ac9486556
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 561b06f7-69b0-4d62-8a2b-fc8d3083fa37
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 83eb98b2-ffa8-47d0-b326-6c7da81ef1c7
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 3c5af4a0-95aa-490f-afcf-fca8cbd468c3
		summarizeBy: sum
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 2851a089-2bbc-4816-beb5-12bd9aa5009f
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: c8c3d6d4-c5c5-47ef-a743-af19722e1d06
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	partition TransactionTable-12e9cb93-5464-4d16-8a56-e8bff3c91c08 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Dr. Fairooz Anika\Desktop\Power BI Samples\Financial Sample.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", type number}, {"Discounts", type number}, {" Sales", type number}, {"COGS", type number}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Discount Band", "Discount Category"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Units Sold", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

