table MoviesDirectors
	isHidden
	lineageTag: 83e29438-f78b-4964-834d-44b5a8caccd4

	column MovieID
		dataType: string
		isHidden
		lineageTag: 2a6d00c7-8c68-4c21-b0b4-877f3d86f000
		summarizeBy: none
		sourceColumn: MovieID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DirectorID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e92cfbed-9c20-43e5-967c-69712434b92d
		summarizeBy: none
		sourceColumn: DirectorID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition MoviesDirectors = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Tommy Naughton\AppData\Local\Packages\Microsoft.MicrosoftPowerBIDesktop_8wekyb3d8bbwe\AC\INetCache\E2B7II0F\messyimdb[1]"),[Delimiter=";", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"IMBD title ID", type text}, {"Original titlÊ", type text}, {"Release year", type text}, {"Genrë¨", type text}, {"Duration", type text}, {"Country", type text}, {"Content Rating", type text}, {"Director", type text}, {"", type text}, {"Income", type text}, {" Votes ", type text}, {"Score", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Original titlÊ", "Original Title"}, {"Genrë¨", "Genre"}, {"IMBD title ID", "MovieID"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{""}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Removed Columns",{"MovieID", "Director"}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Other Columns", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Removed Blank Rows", "Director", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), {"Director.1", "Director.2"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Director.1", type text}, {"Director.2", type text}}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Changed Type2", {"MovieID"}, "Attribute", "Value"),
				    #"Removed Columns1" = Table.RemoveColumns(#"Unpivoted Other Columns",{"Attribute"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"Value", "DirectorID"}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Renamed Columns1",{{"DirectorID", Text.Trim, type text}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Trimmed Text",{{"DirectorID", "Director Name"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns2", {"Director Name"}, Director, {"Director Name"}, "Director", JoinKind.LeftOuter),
				    #"Expanded Director" = Table.ExpandTableColumn(#"Merged Queries", "Director", {"DirectorID"}, {"DirectorID"}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Expanded Director",{"Director Name"})
				in
				    #"Removed Columns2"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

