table Calendar
	lineageTag: 28304b59-5446-4f5e-a948-ce1078400e3c
	dataCategory: Time

	column DateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3d0fd66d-e918-4270-b095-3a53de79f230
		summarizeBy: none
		sourceColumn: DateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FullDate
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 79d0f38b-5476-4d23-8dc7-2a4bd97d2cd8
		summarizeBy: none
		sourceColumn: FullDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DayNumberOfWeek
		dataType: int64
		formatString: 0
		lineageTag: fc85158e-b93e-4198-884b-7b2edebbfa2c
		summarizeBy: sum
		sourceColumn: DayNumberOfWeek

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DayNameOfWeek
		dataType: string
		lineageTag: 16af553f-6503-458b-aaec-e7c8a92897b7
		summarizeBy: none
		sourceColumn: DayNameOfWeek
		sortByColumn: DayNumberOfWeek

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column DayNumberOfMonth
		dataType: int64
		formatString: 0
		lineageTag: 564885f5-4233-4aa8-af2e-326758d6f7cd
		summarizeBy: sum
		sourceColumn: DayNumberOfMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DayNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: fb574563-7981-4e0a-9336-e74545e30468
		summarizeBy: sum
		sourceColumn: DayNumberOfYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WeekNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: 5e41b02d-08a7-47c3-8b01-5fa061f27cf5
		summarizeBy: sum
		sourceColumn: WeekNumberOfYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 33bfecca-5ce4-4807-8cf8-cca71adc60e6
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: MonthNumberOfYear

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column MonthNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: ca4c822d-07f1-4603-9723-4a7a894fb20a
		summarizeBy: sum
		sourceColumn: MonthNumberOfYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CalendarQuarter
		dataType: int64
		formatString: 0
		lineageTag: db548837-65d3-4f7c-a57e-b570a29af7b4
		summarizeBy: sum
		sourceColumn: CalendarQuarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CalendarYear
		dataType: int64
		formatString: 0
		lineageTag: 82c3603b-bce5-4a4b-8b4a-7eb79bc8d137
		summarizeBy: sum
		sourceColumn: CalendarYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CalendarSemester
		dataType: int64
		formatString: 0
		lineageTag: 0ed18a87-1831-4dcf-84cb-aa758b6ea39f
		summarizeBy: sum
		sourceColumn: CalendarSemester

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FiscalQuarter
		dataType: int64
		formatString: 0
		lineageTag: d10634ff-17fa-426d-ac62-a1e40a45735d
		summarizeBy: sum
		sourceColumn: FiscalQuarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: int64
		formatString: 0
		lineageTag: 01b567f1-0972-4b00-b25d-f79ef8cc780b
		summarizeBy: sum
		sourceColumn: FiscalYear

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FiscalSemester
		dataType: int64
		formatString: 0
		lineageTag: 5d76402b-942f-4e4d-bf1c-ee1a7d0e93b1
		summarizeBy: sum
		sourceColumn: FiscalSemester

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Calendar = m
		mode: import
		source =
				let
				    Source = Sql.Database("bpbi.database.windows.net", "BPBI"),
				    DW_Calendar = Source{[Schema="DW",Item="Calendar"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(DW_Calendar,{{"EnglishMonthName", "MonthName"}, {"EnglishDayNameOfWeek", "DayNameOfWeek"}})
				in
				    #"Renamed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

